import os
os.system ("clear")

QUANTIDADE_DE_NUMEROS = 5
lista_numeros = []
qunatidade_negativo = 0
qunatidade_positivo = 0

def soma_positivos(lista):
    soma += lista
    return soma
    
print("= Solicitando números =")    
for i in range (QUANTIDADE_DE_NUMEROS):
  numero = int(input("Digite o {i=1}° número"))
  lista_numeros.append(numero)
  
for numero < 0 lista_numeros:
  if numero < 0:
    qunatidade_negativo  += 1
  else:
soma_positivos += 1















print(f"Número dsistivo{positivo}")