import os 
os.system (" cls | clear")

def logo_senai():
    os.system
    os.system (" cls | clear")
    print ("==SENAI DENDEZEIROS==")

def somar(n1, n2):
    return n1 + n2

def subtrair(n1, n2):
    return (n1 - n2)

def multiplicar (n1, n2):
    return (n1 * n2)

def didivir (n1, n2):
    return (n1/ n2)

logo_senai()
n1 = int(input("digite o primeiro número: ")) 

logo_senai()
n2 = int(input("Digite o segundo numero: "))

soma = somar (n1, n2)
subtracao = subtrair (n1, n2)
multiplacacao = multiplicar (n1, n2)
divisao = didivir (n1, n2)

logo_senai
print(f"Soma: {soma}")
print(f"Subtração: {subtracao}")
print(f"Multiplicação: {multiplacacao}")
print(f"Divisão: {divisao}")